### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [lmaxwell/chuckComposition#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under the [DAW section](https://github.com/forart/HyMPS/blob/main/DAWs.md#subsections)), can you please fix licensing terms for it ?

Our "problem" is that does not generates a correct badge:

![](https://flat.badgen.net/github/license/lmaxwell/guiless-daw/?label=LICENSE)
(generate url: https://flat.badgen.net/github/license/lmaxwell/guiless-daw/?label=LICENSE)

This could easily be fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this could help other devs to understand how reuse your code in other open projects and vice-versa.

Last but not least, let us know how (in your opinion) we could improve our categorizations and links to resources in order to favor collaboration (and therefore evolution) between developers of listed projects.

Thanks in advance.

**Comment by lmaxwell** [comment]
Hi, I'm so happy for your attention on this work,  have added a licence #2

**Comment by MarcoRavich** [comment]
First of all, thanks for the timely fix!

As you can see (above too) the badge is correctly generated now.

Thanks again and, if you like/need, let us know (by replying to [our discussions](https://github.com/forart/HyMPS/discussions)) how we can support listed projects.

Last but not least, Happy New Year !
